// CITIES //

export const GET_CITIES = "GET_CITIES"
export const CITIES_LOADING = "CITIES_LOADING"
export const ADD_CITY = "ADD_CITY"
export const ADD_SUCCESS = "ADD_SUCCESS"
export const DELETE_CITY = "DELETE_CITY"
export const UPDATE_CITY = "UPDATE_CITY"

// ITINERARIES //
export const GET_ITINERARIES = "GET_ITINERARIES"
export const ITINERARIES_LOADING = "ITINERARIES_LOADING"
export const ADD_ITINERARY = "ADD_ITINERARY"
export const ADD_IT_SUCCESS = "ADD_IT_SUCCESS"
export const DELETE_ITINERARY = "DELETE_ITINERARY"
export const UPDATE_ITINERARY = "UPDATE_ITINERARY"

// ACTIVITIES //
export const GET_ACTIVITIES = "GET_ACTIVITIES"
export const ACTIVITIES_LOADING = "ACTIVITIES_LOADING"
export const ADD_ACTIVITY = "ADD_ACTIVITY"
export const ADD_AC_SUCCESS = "ADD_AC_SUCCESS"
/* export const DELETE_ACTIVITY = "DELETE_ACTIVITY"
export const UPDATE_ACTIVITY = "UPDATE_ACTIVITY" */

// COMMENTS //
export const GET_COMMENTS = "GET_COMMENTS"
export const COMMENTS_LOADING = "COMMENTS_LOADING"
export const ADD_COMMENT = "ADD_COMMENT"
export const DELETE_COMMENT = "DELETE_COMMENT"
/* export const UPDATE_COMMENT = "UPDATE_COMMENT" */


// AUTH //
export const USER_LOADING = "USER_LOADING"
export const USER_LOADED = "USER_LOADED"
export const AUTH_ERROR = "AUTH_ERROR"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS"
export const REGISTRATION_FAIL = "REGISTRATION_FAIL"

// ERRORS //
export const GET_ERRORS = "GET_ERRORS"
export const CLEAR_ERRORS = "CLEAR_ERRORS"


